services: 

  app:
    container_name: "docker-lamp"
    environment:  
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASS=${DB_PASS}
      - DB_USERNAME=${DB_USERNAME}
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT-8080}:80" 
    volumes:
      - ./src/:/var/www/html  
       